version: '2.1'

services:
  bears-project-3:
    image: bears-project-3
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js