version: '3'
services:
  server:
    image: node:10.14.2-alpine
    user: node
    working_dir: /var/app
    volumes:
      - ./:/var/app
    ports:
      - 3001:3030
    environment:
      - NODE_ENV=development
    expose:
      - 3030
    links:
      - prisma
      - postgres
    depends_on:
      - postgres
      - prisma
    command: >
      sh -c "yarn && yarn start"

  prisma:
    container_name: bears03-prisma
    image: prismagraphql/prisma:1.22
    restart: always
    ports:
    - "7777:7777"
    environment:
      PRISMA_CONFIG: |
        port: 7777
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true

  postgres:
    container_name: bears03-postgres
    image: postgres:10.5
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
